### ISSUE TITLE
Per-Commit stepping and baseline improvement

### ISSUE THREAD

**Issue by Byron** [Byron/crates-index-diff-rs#30]
Various tasks offloaded from #26 with the main purpose of restoring the correct order of crate changes and updating the baseline tests to be more realistic.

### Tasks

1. [x] add support for per-commit stepping to allow for orderly discovery of changes
2. [x] improve baseline to test big steps and one-commit-per-step (using the new API of above) like `---x---x---xxx`
3. [x] adjust baseline test to inform about the `yanked` status as well, so we expect that all _changes_ leave us as exactly the right information about the versions still in existence and their yanked status.
